/**
Author: Eesha Jain
In behalf of Nanodropper Inc.

Autogenerated by Expo
**/

//Dictionary of colors
export default {
  light: {
    text: '#000',
    background: '#fff',
    tabBackground: '#eee',
    tint: '#2f95dc',
    tabIconDefault: '#666',
    tabIconSelected: '#2f95dc',
    teal: 'rgb(0, 148, 162)',
    blue: '#2A3B9F',
    white: '#FFF',
    red: 'red',
    appointment: '#ADD8E6',
    lightgray: 'rgb(242, 242, 242)',
    mediumgray: 'rgb(153, 153, 153)',
    darkgray: 'rgb(179, 179, 179)',
    inputgray: 'rgb(77, 77, 77)',
    gradient: 'linear-gradient(to right, rgb(0, 148, 162), #2A3B9F)',
    gradientone: 'rgb(0, 148, 162)',
    gradienttwo: '#2A3B9F',
    notcompleted: '#83bcb5',
    completed: '#00a9d6',
    coffeeicons: "#2A3B9F",
    textinput: 'transparent',
    today: '#fcbc58',
    drop1: '#1026a3',
    drop2: '#7f7dde',
    drop3: '#505fbf',
    drop4: '#5d8abd',
    future: 'rgb(255, 255, 255)',
    noton: 'rgb(204, 204, 204)'
  },
  dark: {
    text: '#fff',
    background: '#000',
    tabBackground: '#20303b',
    tint: '#2f95dc',
    tabIconDefault: '#efefef',
    tabIconSelected: '#7dcaff',
    teal: '#007985',
    appointment: '#0d3b4a',
    blue: '#7dcaff',
    red: '#ff7878',
    white: '#000',
    coffeeicons: "#7482d4",
    lightgray: '#303030',
    mediumgray: '#696969',
    darkgray: 'rgb(179, 179, 179)',
    inputgray: '#c4c4c4',
    textinput: 'rgb(242, 242, 242)',
    gradient: 'linear-gradient(to right, #0895a3, #455bd9)',
    gradientone: '#0895a3',
    gradienttwo: '#455bd9',
    notcompleted: '#4a6965',
    completed: '#005369',
    drop1: '#304fff',
    drop2: '#7f7dde',
    drop3: '#505fbf',
    drop4: '#5d8abd',
    today: '#b57b21',
    future: 'black',
    noton: '#575757'
  }
};
